INSERT INTO track VALUES ('linear-algebra', 'Álgebra Lineal', 'Vectores, matrices y transformaciones', 'Espacios vectoriales, matrices, autovalores y descomposiciones: la matemática que hay bajo los gráficos y el aprendizaje automático.', 'math', 'indexed', '#cba6f7', '#cba6f7', '#94e2d5', 2, NULL, NULL);
INSERT INTO track VALUES ('algoritmos', 'Algoritmos', 'Diseño, análisis y técnicas', 'Divide y vencerás, programación dinámica, voraces, grafos y flujos, con el análisis de coste como hilo conductor.', 'algoritmos-datos', 'indexed', '#94e2d5', '#94e2d5', '#b4befe', 0, NULL, NULL);
INSERT INTO track VALUES ('android', 'Android', 'Jetpack Compose y la plataforma', 'Desarrollo Android completo: Jetpack Compose y UI adaptativa, las librerías de Jetpack (Room, WorkManager, Paging), capacidades del sistema, rendimiento y Google Play.', 'mobile', 'written', '#a6e3a1', '#a6e3a1', '#94e2d5', 0, NULL, NULL);
INSERT INTO track VALUES ('animacion', 'Animación Web', 'Del transition al ScrollTrigger', 'El movimiento en la web: el pipeline del navegador, transitions y keyframes, WAAPI, scroll-driven, view transitions y GSAP a fondo.', 'frontend', 'written', '#f5c2e7', '#f5c2e7', '#cba6f7', 1, NULL, NULL);
INSERT INTO track VALUES ('astro', 'Astro 7', 'El framework web content-first', 'De islands architecture a producción: componentes, content collections, SSR/SSG, actions, view transitions, el compilador en Rust y desplegar en el edge.', 'frontend', 'written', '#cba6f7', '#cba6f7', '#f5c2e7', 7, NULL, NULL);
INSERT INTO track VALUES ('bash', 'Bash y el Shell', 'El lenguaje del sistema', 'El shell como lenguaje: expansión, redirección, procesos, señales, y scripts que no se rompen con un espacio.', 'entorno-desarrollo', 'indexed', '#fab387', '#fab387', '#f5c2e7', 0, NULL, NULL);
INSERT INTO track VALUES ('build', 'Build & Producción', 'De pnpm a producción', 'El camino a producción: pnpm, módulos, Vite y Rolldown, bundling, code splitting, lazy loading, monorepos y remote caching (Turborepo/Nx).', 'entorno-desarrollo', 'written', '#94e2d5', '#94e2d5', '#a6e3a1', 9, NULL, NULL);
INSERT INTO track VALUES ('c23', 'C23 moderno', 'El lenguaje y su entorno de sistemas', 'De la sintaxis de C23 al nivel PhD: punteros, memoria, Meson, sanitizers, ABI, libc/musl, freestanding, concurrencia y tu propia libc.', 'lenguajes', 'written', '#89b4fa', '#89b4fa', '#74c7ec', 3, NULL, NULL);
INSERT INTO track VALUES ('canvas', 'Canvas y SVG', 'Gráficos 2D y visualización', 'Los dos modelos del gráfico 2D: el contexto de canvas, píxeles y composición, SVG a fondo, filtros, y la visualización de datos.', 'frontend', 'written', '#a6e3a1', '#a6e3a1', '#94e2d5', 4, NULL, NULL);
INSERT INTO track VALUES ('cloudflare', 'Cloudflare', 'La plataforma del edge', 'La plataforma developer de Cloudflare: Workers (isolates), D1, R2, KV, Durable Objects, Queues, Workers AI, Vectorize, Hyperdrive, Pages y Wrangler.', 'cloud', 'written', '#fab387', '#fab387', '#f9e2af', 0, NULL, NULL);
INSERT INTO track VALUES ('complejidad', 'Complejidad Computacional', 'Clases, reducciones y límites', 'P, NP, reducciones, completitud y jerarquías: qué se puede resolver de forma eficiente y qué no.', 'teoria-computacion', 'indexed', '#f5c2e7', '#f5c2e7', '#eba0ac', 2, NULL, NULL);
INSERT INTO track VALUES ('computabilidad', 'Computabilidad y Autómatas', 'Lo que una máquina puede decidir', 'Autómatas, lenguajes formales, máquinas de Turing, indecidibilidad y el problema de la parada.', 'teoria-computacion', 'indexed', '#b4befe', '#b4befe', '#a6e3a1', 3, NULL, NULL);
INSERT INTO track VALUES ('concurrencia', 'Concurrencia', 'Modelos de ejecución simultánea', 'Memoria compartida frente a paso de mensajes, exclusión mutua, modelos de memoria, y los teoremas de imposibilidad.', 'concurrencia-distribuidos', 'indexed', '#eba0ac', '#eba0ac', '#cba6f7', 5, NULL, NULL);
INSERT INTO track VALUES ('consistencia', 'Consistencia y Particionado', 'Qué se sacrifica y cuándo', 'Modelos de consistencia, particionado, replicación y las decisiones que impone el teorema CAP en un sistema real.', 'system-design', 'indexed', '#cba6f7', '#cba6f7', '#94e2d5', 4, NULL, NULL);
INSERT INTO track VALUES ('css', 'CSS Moderno', 'La cascada, el layout y el color de 2026', 'CSS de verdad: cascada y capas, :has, nesting, @scope, grid y subgrid, container queries, OKLCH, anchor positioning, arquitectura y rendimiento.', 'frontend', 'written', '#89b4fa', '#89b4fa', '#cba6f7', 0, NULL, NULL);
INSERT INTO track VALUES ('devtools', 'Chrome DevTools', 'El método de depuración', 'Las herramientas por dentro: Elements y la cascada real, breakpoints que no son de línea, el waterfall, el flame chart, cazar fugas y automatizar.', 'entorno-desarrollo', 'written', '#74c7ec', '#74c7ec', '#89b4fa', 6, NULL, NULL);
INSERT INTO track VALUES ('diseno-apis', 'Diseño de APIs', 'El contrato que no puedes romper', 'Recursos, versionado, paginación, idempotencia, errores y evolución de un contrato con clientes que no controlas.', 'system-design', 'indexed', '#89dceb', '#89dceb', '#f9e2af', 5, NULL, NULL);
INSERT INTO track VALUES ('dotfiles', 'Dotfiles', 'Tu entorno, reproducible', 'Versionar la configuración, gestionarla entre máquinas, y el arranque de un equipo nuevo en minutos.', 'entorno-desarrollo', 'indexed', '#b4befe', '#b4befe', '#a6e3a1', 4, NULL, NULL);
INSERT INTO track VALUES ('drivers-io', 'Entrada/Salida y Drivers', 'Hablar con el hardware', 'El modelo de dispositivos, DMA, interrupciones, buses y cómo un driver expone hardware como una abstracción del sistema.', 'sistemas-operativos', 'indexed', '#b4befe', '#b4befe', '#a6e3a1', 5, NULL, NULL);
INSERT INTO track VALUES ('elm', 'The Elm Architecture', 'El origen del flujo unidireccional', 'Elm y TEA: el lenguaje funcional puro sin errores en runtime, Model/update/view, los efectos como datos, y el legado que sembró en Redux, TCA y MVI.', 'reactividad', 'written', '#a6e3a1', '#a6e3a1', '#94e2d5', 4, NULL, NULL);
INSERT INTO track VALUES ('estado', 'Fundamentos de Estado', 'Signals, derivación y el estado del servidor', 'Los cimientos de la reactividad: signals y observables, derivación, inmutabilidad, sincronización, el estado del servidor, la URL, formularios y local-first.', 'reactividad', 'written', '#b4befe', '#b4befe', '#89dceb', 1, NULL, NULL);
INSERT INTO track VALUES ('estructuras-datos', 'Estructuras de Datos', 'De la lista al árbol de búsqueda', 'Listas, pilas, tablas hash, árboles equilibrados, montículos y estructuras persistentes, con sus costes amortizados.', 'algoritmos-datos', 'indexed', '#f9e2af', '#f9e2af', '#74c7ec', 1, NULL, NULL);
INSERT INTO track VALUES ('event-driven', 'Arquitecturas Dirigidas por Eventos', 'El log como fuente de verdad', 'Colas, log de eventos, event sourcing, CQRS, entrega al menos una vez y el diseño para el reprocesado.', 'system-design', 'indexed', '#a6e3a1', '#a6e3a1', '#89dceb', 2, NULL, NULL);
INSERT INTO track VALUES ('flux', 'Flux y Redux', 'El flujo unidireccional en la web', 'De Flux a Redux Toolkit y la ola ligera: store, reducers, middleware, selectores, RTK Query, DevTools, y Zustand/Jotai/Valtio a fondo.', 'reactividad', 'written', '#cba6f7', '#cba6f7', '#b4befe', 3, NULL, NULL);
INSERT INTO track VALUES ('fzf-ripgrep', 'Búsqueda en el Terminal', 'fzf, ripgrep y fd', 'Búsqueda difusa, expresiones regulares a escala, y componer herramientas para encontrar cualquier cosa en segundos.', 'entorno-desarrollo', 'indexed', '#f9e2af', '#f9e2af', '#74c7ec', 2, NULL, NULL);
INSERT INTO track VALUES ('git', 'Git a Fondo', 'El grafo, no los comandos', 'El modelo de objetos, el grafo de commits, rebase, reflog y resolver cualquier situación entendiendo qué hay debajo.', 'entorno-desarrollo', 'indexed', '#94e2d5', '#94e2d5', '#b4befe', 1, NULL, NULL);
INSERT INTO track VALUES ('ios', 'iOS', 'Apps para el ecosistema Apple', 'Desarrollo iOS completo: SwiftUI y su modelo declarativo, SwiftData y persistencia, arquitectura, capacidades del sistema, rendimiento y publicar en la App Store.', 'mobile', 'written', '#f5c2e7', '#f5c2e7', '#cba6f7', 1, NULL, NULL);
INSERT INTO track VALUES ('kernel', 'Kernel de Linux', 'C del kernel, tooling y Rust for Linux', 'El corazón del sistema operativo: Kbuild, módulos, drivers, RCU, memoria del kernel, depuración y el nuevo Rust como lenguaje central.', 'systems', 'written', '#f9e2af', '#f9e2af', '#fab387', 0, NULL, NULL);
INSERT INTO track VALUES ('kotlin', 'Kotlin', 'El lenguaje, del null safety a K2', 'Kotlin como lenguaje: nulabilidad en el sistema de tipos, sealed y exhaustividad, genéricos y varianza, DSLs, corrutinas y Flow por dentro, el compilador K2 y los cuatro backends.', 'lenguajes', 'written', '#cba6f7', '#cba6f7', '#89b4fa', 1, NULL, NULL);
INSERT INTO track VALUES ('local-first', 'Local-First', 'Arquitectura de datos que viven en el cliente', 'La arquitectura local-first a fondo: almacenamiento en el navegador y SQLite sobre OPFS, Web Workers, la teoría de los CRDT y sus algoritmos de secuencia, almacenamiento direccionado por contenido, motores de sincronización, identidad sin servidor y cifrado extremo a extremo.', 'local-first', 'written', '#94e2d5', '#94e2d5', '#74c7ec', 4, NULL, NULL);
INSERT INTO track VALUES ('logic', 'Lógica', 'Proposicional, de primer orden y demostración', 'Lógica proposicional y de primer orden, sistemas de deducción, y la correspondencia entre demostraciones y programas.', 'math', 'indexed', '#89b4fa', '#89b4fa', '#fab387', 1, NULL, NULL);
INSERT INTO track VALUES ('lua', 'Lua', 'El lenguaje mínimo que está en todas partes', 'Lua a fondo: tablas y metatablas, closures y upvalues, corrutinas, el recolector y la máquina virtual de registros, la API C, embeber el lenguaje y LuaJIT.', 'lenguajes', 'written', '#89b4fa', '#89b4fa', '#b4befe', 2, NULL, NULL);
INSERT INTO track VALUES ('maquinas', 'Máquinas de Estado', 'FSM, statecharts y XState', 'Modelar el estado como una máquina: autómatas, statecharts de Harel, XState v5 a fondo, el actor model, testing basado en modelos y patrones reales.', 'reactividad', 'written', '#89dceb', '#89dceb', '#94e2d5', 2, NULL, NULL);
INSERT INTO track VALUES ('discrete-math', 'Matemática Discreta', 'Conjuntos, relaciones, grafos y recurrencias', 'La base combinatoria del razonamiento sobre programas: conjuntos, relaciones, grafos, recurrencias e inducción.', 'math', 'written', '#a6e3a1', '#a6e3a1', '#89dceb', 0, NULL, NULL);
INSERT INTO track VALUES ('memoria-virtual', 'Memoria Virtual', 'Direcciones, páginas y fallos', 'Paginación, la TLB, el fallo de página, la asignación de memoria y por qué tu puntero no apunta a la RAM.', 'sistemas-operativos', 'indexed', '#fab387', '#fab387', '#f5c2e7', 1, NULL, NULL);
INSERT INTO track VALUES ('microkernels', 'Arquitecturas de Núcleo', 'Monolítico, micro e híbrido', 'Monolítico frente a microkernel, exokernels, unikernels y qué se gana y se pierde en cada reparto de responsabilidades.', 'sistemas-operativos', 'indexed', '#f5c2e7', '#f5c2e7', '#eba0ac', 4, NULL, NULL);
INSERT INTO track VALUES ('microservicios', 'Microservicios', 'Repartir para escalar', 'Descomposición por dominio, comunicación entre servicios, transacciones distribuidas, y el coste operativo que se compra.', 'system-design', 'indexed', '#eba0ac', '#eba0ac', '#cba6f7', 1, NULL, NULL);
INSERT INTO track VALUES ('monolitos', 'Monolitos y Modularidad', 'Un despliegue, muchos módulos', 'El monolito modular, los límites internos, cuándo la modularidad basta y qué problema resuelve de verdad partir un sistema.', 'system-design', 'indexed', '#74c7ec', '#74c7ec', '#89b4fa', 0, NULL, NULL);
INSERT INTO track VALUES ('mvi', 'MVI y Orbit', 'Flujo unidireccional en Kotlin', 'Model-View-Intent en el mundo Android: Orbit, coroutines y Flow, estado inmutable en Compose, side effects de una sola vez y Kotlin Multiplatform.', 'reactividad', 'written', '#94e2d5', '#94e2d5', '#a6e3a1', 6, NULL, NULL);
INSERT INTO track VALUES ('neovim', 'Neovim', 'El editor a la velocidad del pensamiento', 'Del modelo modal a tu propia config en Lua: un IDE para C/Rust/Swift/Frontend, terminal, automatización e IA.', 'entorno-desarrollo', 'written', '#cba6f7', '#cba6f7', '#89b4fa', 0, '/config/', '/resources/');
INSERT INTO track VALUES ('probability', 'Probabilidad y Estadística', 'Aleatoriedad, distribuciones e inferencia', 'Probabilidad, variables aleatorias, distribuciones e inferencia, con el análisis de algoritmos aleatorizados como motivación.', 'math', 'indexed', '#89dceb', '#89dceb', '#f9e2af', 3, NULL, NULL);
INSERT INTO track VALUES ('procesos', 'Procesos y Planificación', 'Qué corre y cuándo', 'Procesos e hilos, cambio de contexto, planificadores, prioridades y el coste real de la concurrencia en el sistema.', 'sistemas-operativos', 'indexed', '#89dceb', '#89dceb', '#f9e2af', 0, NULL, NULL);
INSERT INTO track VALUES ('programacion-reactiva', 'Programación Reactiva', 'El paradigma, no la librería', 'El modelo de propagación: grafos de dependencias, tracking, consistencia glitch-free, y qué distingue push de pull.', 'lenguajes-tipos', 'indexed', '#89b4fa', '#89b4fa', '#fab387', 7, NULL, NULL);
INSERT INTO track VALUES ('reactividad-fina', 'Motores de Reactividad', 'El grafo, el dueño y la propagación', 'Cómo funciona un motor de reactividad por dentro: el grafo de dependencias, tracking automático, push-pull, glitches, el árbol de dueños y los motores comparados.', 'reactividad', 'written', '#b4befe', '#b4befe', '#89b4fa', 0, NULL, NULL);
INSERT INTO track VALUES ('rendimiento', 'Rendimiento Web', 'Core Web Vitals y el hilo principal', 'Hacer que vaya rápido de verdad: LCP, INP y CLS, la red y la caché, el coste del JavaScript, el pipeline de render, memoria y estrategias de carga.', 'frontend', 'written', '#f9e2af', '#f9e2af', '#fab387', 5, NULL, NULL);
INSERT INTO track VALUES ('rust', 'Rust', 'Sistemas seguros, del ownership al kernel', 'Ownership, traits, lifetimes, async (edición 2024), unsafe/FFI, no_std, embebido, debugging y programación a nivel de tipos.', 'lenguajes', 'written', '#fab387', '#fab387', '#eba0ac', 4, NULL, NULL);
INSERT INTO track VALUES ('sistemas-distribuidos', 'Sistemas Distribuidos', 'Consenso, tiempo y fallos', 'Relojes lógicos, consenso, replicación, tolerancia a fallos, CAP y los CRDT como teoría antes que como librería.', 'concurrencia-distribuidos', 'indexed', '#a6e3a1', '#a6e3a1', '#89dceb', 6, NULL, NULL);
INSERT INTO track VALUES ('sistemas-ficheros', 'Sistemas de Ficheros', 'Del inodo al journal', 'Inodos, journaling, cachés, sincronización a disco y las garantías reales que ofrece cada sistema de ficheros.', 'sistemas-operativos', 'indexed', '#94e2d5', '#94e2d5', '#b4befe', 2, NULL, NULL);
INSERT INTO track VALUES ('solid', 'SolidJS', 'Reactividad fina, del signal al fullstack', 'Reactividad de grano fino: signals, efectos, memos, stores, control flow, createResource, Solid 2.0 (async first-class) y SolidStart.', 'frontend', 'written', '#89b4fa', '#89b4fa', '#74c7ec', 8, NULL, NULL);
INSERT INTO track VALUES ('swift', 'Swift', 'El lenguaje, de la sintaxis al compilador', 'Swift 6 a fondo: el modelo de tipos y valores, protocolos y genéricos, macros y result builders, memoria y ownership, concurrencia estricta, y Swift fuera de Apple.', 'lenguajes', 'written', '#fab387', '#fab387', '#f38ba8', 0, NULL, NULL);
INSERT INTO track VALUES ('syscalls', 'Syscalls y la Frontera', 'El contrato con el núcleo', 'La interfaz entre el espacio de usuario y el núcleo: syscalls, interrupciones, copias de memoria y el coste del cruce.', 'sistemas-operativos', 'indexed', '#f9e2af', '#f9e2af', '#74c7ec', 3, NULL, NULL);
INSERT INTO track VALUES ('tca', 'Composable Architecture', 'TCA: arquitectura y testing en Swift', 'The Composable Architecture de Point-Free: State, Action, Reducer, Effect y Store; composición, @Dependency, navegación como dato y testing exhaustivo.', 'reactividad', 'written', '#f38ba8', '#f38ba8', '#fab387', 5, NULL, NULL);
INSERT INTO track VALUES ('teoria-lenguajes', 'Teoría de Lenguajes y Compiladores', 'De la gramática al código máquina', 'Gramáticas, análisis léxico y sintáctico, semántica, representaciones intermedias, optimización y generación de código.', 'lenguajes-tipos', 'indexed', '#cba6f7', '#cba6f7', '#94e2d5', 8, NULL, NULL);
INSERT INTO track VALUES ('number-theory', 'Teoría de Números', 'Aritmética modular y sus aplicaciones', 'Divisibilidad, aritmética modular, primalidad y logaritmo discreto: los cimientos de la criptografía moderna.', 'math', 'indexed', '#fab387', '#fab387', '#f5c2e7', 4, NULL, NULL);
INSERT INTO track VALUES ('teoria-tipos', 'Teoría de Tipos', 'Tipos, inferencia y corrección', 'Cálculo lambda, sistemas de tipos, inferencia, polimorfismo y tipos dependientes, y por qué un tipo es una demostración.', 'lenguajes-tipos', 'indexed', '#74c7ec', '#74c7ec', '#89b4fa', 4, NULL, NULL);
INSERT INTO track VALUES ('three', 'Three.js y 3D', 'De la matriz al shader', 'Gráficos 3D en la web: el pipeline, geometría e instancing, PBR y texturas, glTF, shaders GLSL, TSL con WebGPURenderer y producción.', 'frontend', 'written', '#94e2d5', '#94e2d5', '#89dceb', 2, NULL, NULL);
INSERT INTO track VALUES ('tmux', 'Multiplexores', 'tmux y zellij', 'Sesiones persistentes, paneles, sesionizadores y un flujo de trabajo que sobrevive a cerrar el portátil.', 'entorno-desarrollo', 'indexed', '#f5c2e7', '#f5c2e7', '#eba0ac', 3, NULL, NULL);
INSERT INTO track VALUES ('webgpu', 'WebGPU', 'La GPU sin intermediarios', 'La API gráfica moderna de la web: adaptador y dispositivo, buffers y bind groups, WGSL a fondo, compute shaders, GPGPU y arquitecturas de render.', 'frontend', 'written', '#fab387', '#fab387', '#f9e2af', 3, NULL, NULL);

INSERT INTO track_feature VALUES ('c23', 0, '🧠', 'Punteros y memoria', 'El concepto que define a C, la gestión manual del heap y las estrategias que escalan.');
INSERT INTO track_feature VALUES ('c23', 1, '✨', 'C23 moderno', 'constexpr, nullptr, typeof, _BitInt, #embed: el C de siempre, más afilado.');
INSERT INTO track_feature VALUES ('c23', 2, '🏗️', 'Build y linking', 'Meson, Make, bibliotecas .a/.so, el linker y el formato ELF por dentro.');
INSERT INTO track_feature VALUES ('c23', 3, '🔗', 'ABI', 'Las convenciones de llamada y la interfaz binaria que une el software compilado.');
INSERT INTO track_feature VALUES ('c23', 4, '📚', 'libc y freestanding', 'glibc vs musl, las syscalls, y el mundo sin libc: bare metal.');
INSERT INTO track_feature VALUES ('c23', 5, '🛡️', 'Sanitizers y fuzzing', 'ASan, UBSan, análisis estático y fuzzing: caza bugs antes de que ocurran.');
INSERT INTO track_feature VALUES ('c23', 6, '⚡', 'Concurrencia y bajo nivel', 'Atomics, el modelo de memoria, SIMD, caché y perf.');
INSERT INTO track_feature VALUES ('c23', 7, '🔱', 'Nivel PhD', 'Tu propia libc, un allocator desde cero, y cómo funciona un compilador.');
INSERT INTO track_feature VALUES ('kernel', 0, '🐧', 'El C del kernel', 'GNU C freestanding, sin libc, con su propio universo de APIs y reglas.');
INSERT INTO track_feature VALUES ('kernel', 1, '🔧', 'Kbuild y módulos', 'Configurar y compilar el kernel, y escribir módulos cargables (LKM).');
INSERT INTO track_feature VALUES ('kernel', 2, '📟', 'Drivers y char devices', 'file_operations, el device model y hablar con el hardware.');
INSERT INTO track_feature VALUES ('kernel', 3, '🔒', 'Concurrencia extrema', 'Spinlocks, mutexes, RCU y las barreras de memoria que escalan a miles de núcleos.');
INSERT INTO track_feature VALUES ('kernel', 4, '🧠', 'Memoria del kernel', 'kmalloc, el slab allocator, páginas y memoria física.');
INSERT INTO track_feature VALUES ('kernel', 5, '⚡', 'Interrupciones', 'IRQ handlers, softirqs, tasklets, workqueues y el planificador.');
INSERT INTO track_feature VALUES ('kernel', 6, '🐞', 'Depuración', 'ftrace, KASAN, lockdep, kgdb: cazar bugs en el corazón del sistema.');
INSERT INTO track_feature VALUES ('kernel', 7, '🦀', 'Rust for Linux', 'El nuevo lenguaje central del kernel: drivers seguros en Rust.');
INSERT INTO track_feature VALUES ('discrete-math', 0, '🧩', 'El lenguaje común', 'Conjuntos, lógica y relaciones: el vocabulario con el que están escritos los papers que quieres leer.');
INSERT INTO track_feature VALUES ('discrete-math', 1, '🪜', 'Inducción e invariantes', 'La demostración que se parece a tu función recursiva, y la que corre dentro de tu bucle.');
INSERT INTO track_feature VALUES ('discrete-math', 2, '🔢', 'Contar sin enumerar', 'Combinatoria, palomar e inclusión-exclusión: por qué las colisiones de hash son inevitables.');
INSERT INTO track_feature VALUES ('discrete-math', 3, '🕸️', 'Grafos de verdad', 'Del DAG de tu build al orden topológico, la conectividad y el coloreado de registros.');
INSERT INTO track_feature VALUES ('discrete-math', 4, '♻️', 'Recurrencias', 'Del teorema maestro al coste real de partir un problema por la mitad.');
INSERT INTO track_feature VALUES ('discrete-math', 5, '🔗', 'Retículos y CRDT', 'Las tres propiedades algebraicas que hacen converger un estado replicado.');
INSERT INTO track_feature VALUES ('neovim', 0,'⌨️', 'La gramática de Vim', 'Operadores + mociones + objetos de texto. Deja de memorizar atajos y empieza a "hablar" el idioma de la edición.');
INSERT INTO track_feature VALUES ('neovim', 1, '🧠', 'LSP nativo 0.12', 'vim.lsp.enable, Mason, diagnósticos y code actions. El motor de un IDE moderno, sin la pesadez.');
INSERT INTO track_feature VALUES ('neovim', 2, '⚡', 'blink.cmp', 'Autocompletado en Rust, fuzzy tolerante a typos y 0.5–4 ms por pulsación.');
INSERT INTO track_feature VALUES ('neovim', 3, '🌳', 'Treesitter', 'Resaltado semántico, objetos de texto inteligentes y selección incremental.');
INSERT INTO track_feature VALUES ('neovim', 4, '🪟', 'tmux + zellij', 'Multiplexores, navegación transparente entre paneles y sesionizadores.');
INSERT INTO track_feature VALUES ('neovim', 5, '🤖', 'IA por capas', 'Copilot/Supermaven, Avante/CodeCompanion y Claude Code integrados en tu flujo.');
INSERT INTO track_feature VALUES ('neovim', 6, '🦀', '4 stacks afinados', 'clangd, rustaceanvim, sourcekit-lsp y el trío React/Tailwind/TS.');
INSERT INTO track_feature VALUES ('neovim', 7, '♻️', 'Automatización total', 'Macros, registros, quickfix, :g y :norm. Tareas repetitivas en una tecla.');
INSERT INTO track_feature VALUES ('rust', 0, '🦀', 'Ownership y borrowing', 'El sistema que garantiza seguridad de memoria sin recolector de basura.');
INSERT INTO track_feature VALUES ('rust', 1, '🧩', 'Traits y genéricos', 'Abstracción sin coste, el sistema de tipos más expresivo de los lenguajes de sistemas.');
INSERT INTO track_feature VALUES ('rust', 2, '⏳', 'Lifetimes', 'Cómo el borrow checker demuestra que tus referencias son válidas.');
INSERT INTO track_feature VALUES ('rust', 3, '⚡', 'Async (edición 2024)', 'async/await, futures, tokio y las async closures del edición 2024.');
INSERT INTO track_feature VALUES ('rust', 4, '🔓', 'Unsafe y FFI', 'Cuando necesitas bajar al metal: unsafe, punteros crudos e interop con C.');
INSERT INTO track_feature VALUES ('rust', 5, '🔩', 'no_std y embebido', 'Rust sin librería estándar: embebido, allocators y el kernel.');
INSERT INTO track_feature VALUES ('rust', 6, '🐞', 'Debugging y profiling', 'Las herramientas para depurar y optimizar Rust en producción.');
INSERT INTO track_feature VALUES ('rust', 7, '🔱', 'Metaprogramación', 'Macros y programación a nivel de tipos: el nivel PhD de Rust.');
INSERT INTO track_feature VALUES ('swift', 0, '🔤', 'Swift 6.3', 'El lenguaje moderno de Apple: opcionales, protocolos, genéricos y typed throws.');
INSERT INTO track_feature VALUES ('swift', 1, '🎨', 'SwiftUI declarativo', 'Construye interfaces con estado reactivo: describe el qué, no el cómo.');
INSERT INTO track_feature VALUES ('swift', 2, '👁️', '@Observable', 'El framework Observation: estado reactivo sin boilerplate, con @State como macro.');
INSERT INTO track_feature VALUES ('swift', 3, '🗄️', 'SwiftData', 'Persistencia con @Model y @Query: sin .xcdatamodeld ni NSManagedObject.');
INSERT INTO track_feature VALUES ('swift', 4, '⚡', 'Concurrencia Swift 6', 'async/await, actores y Sendable con concurrencia estricta que previene data races.');
INSERT INTO track_feature VALUES ('swift', 5, '🌐', 'Redes modernas', 'URLSession con async/await y Codable para consumir APIs sin dolor.');
INSERT INTO track_feature VALUES ('swift', 6, '🧪', 'Swift Testing', 'El nuevo framework de tests con @Test y #expect, más expresivo que XCTest.');
INSERT INTO track_feature VALUES ('swift', 7, '🚀', 'A la App Store', 'Arquitectura, firmas, TestFlight y publicación: de la idea a la tienda.');

INSERT INTO track_chip VALUES ('c23', 0, 'gcc/clang', '#89b4fa');
INSERT INTO track_chip VALUES ('c23', 1, 'C23', '#74c7ec');
INSERT INTO track_chip VALUES ('c23', 2, 'Meson', '#a6e3a1');
INSERT INTO track_chip VALUES ('c23', 3, 'musl', '#94e2d5');
INSERT INTO track_chip VALUES ('c23', 4, 'ASan', '#fab387');
INSERT INTO track_chip VALUES ('c23', 5, 'ELF', '#f9e2af');
INSERT INTO track_chip VALUES ('c23', 6, 'freestanding', '#cba6f7');
INSERT INTO track_chip VALUES ('c23', 7, 'UB', '#f38ba8');
INSERT INTO track_chip VALUES ('kernel', 0, 'LKM', '#f9e2af');
INSERT INTO track_chip VALUES ('kernel', 1, 'Kbuild', '#fab387');
INSERT INTO track_chip VALUES ('kernel', 2, 'RCU', '#cba6f7');
INSERT INTO track_chip VALUES ('kernel', 3, 'kmalloc', '#89b4fa');
INSERT INTO track_chip VALUES ('kernel', 4, 'IRQ', '#f38ba8');
INSERT INTO track_chip VALUES ('kernel', 5, 'ftrace', '#a6e3a1');
INSERT INTO track_chip VALUES ('kernel', 6, 'Rust', '#eba0ac');
INSERT INTO track_chip VALUES ('kernel', 7, 'QEMU', '#94e2d5');
INSERT INTO track_chip VALUES ('neovim', 0, 'C', '#89b4fa');
INSERT INTO track_chip VALUES ('neovim', 1, 'Rust', '#fab387');
INSERT INTO track_chip VALUES ('neovim', 2, 'Swift', '#f38ba8');
INSERT INTO track_chip VALUES ('neovim', 3, 'React', '#89dceb');
INSERT INTO track_chip VALUES ('neovim', 4, 'TypeScript', '#89b4fa');
INSERT INTO track_chip VALUES ('neovim', 5, 'Tailwind', '#94e2d5');
INSERT INTO track_chip VALUES ('neovim', 6, 'HTML', '#eba0ac');
INSERT INTO track_chip VALUES ('neovim', 7, 'CSS', '#b4befe');
INSERT INTO track_chip VALUES ('rust', 0, 'cargo', '#fab387');
INSERT INTO track_chip VALUES ('rust', 1, 'Ownership', '#eba0ac');
INSERT INTO track_chip VALUES ('rust', 2, 'traits', '#cba6f7');
INSERT INTO track_chip VALUES ('rust', 3, 'async', '#f9e2af');
INSERT INTO track_chip VALUES ('rust', 4, 'no_std', '#89b4fa');
INSERT INTO track_chip VALUES ('rust', 5, 'unsafe', '#f38ba8');
INSERT INTO track_chip VALUES ('rust', 6, 'edición 2024', '#a6e3a1');
INSERT INTO track_chip VALUES ('rust', 7, 'tokio', '#94e2d5');
INSERT INTO track_chip VALUES ('swift', 0, 'Swift 6.3', '#fab387');
INSERT INTO track_chip VALUES ('swift', 1, 'SwiftUI', '#89b4fa');
INSERT INTO track_chip VALUES ('swift', 2, 'SwiftData', '#a6e3a1');
INSERT INTO track_chip VALUES ('swift', 3, 'Observation', '#cba6f7');
INSERT INTO track_chip VALUES ('swift', 4, 'Concurrency', '#f9e2af');
INSERT INTO track_chip VALUES ('swift', 5, 'Xcode 26', '#89dceb');
INSERT INTO track_chip VALUES ('swift', 6, 'iOS 26', '#f5c2e7');
INSERT INTO track_chip VALUES ('swift', 7, 'App Store', '#f38ba8');
INSERT INTO track VALUES ('arquitectura-cpu', 'La CPU', 'Del fetch al retiro', 'Pipeline, predicción, ejecución fuera de orden y el modelo que el ensamblador te enseña.', 'arquitectura-computadores', 'planned', '#fab387', '#fab387', '#f9e2af', 0, NULL, NULL);
INSERT INTO track VALUES ('jerarquia-memoria', 'Jerarquía de Memoria', 'Cachés, latencias y localidad', 'De los registros al disco: por qué la localidad manda y qué cuesta un fallo de caché.', 'arquitectura-computadores', 'planned', '#fab387', '#fab387', '#f9e2af', 1, NULL, NULL);
INSERT INTO track VALUES ('tcp-ip', 'TCP/IP', 'La pila de protocolos', 'IP, TCP, UDP y DNS: cómo se enruta, se entrega y se pierde un paquete.', 'redes', 'planned', '#89dceb', '#89dceb', '#74c7ec', 0, NULL, NULL);
INSERT INTO track VALUES ('http-web', 'HTTP y la Web', 'El protocolo de la web', 'De HTTP/1.1 a HTTP/3: semántica, caché, TLS y lo que un navegador negocia por ti.', 'redes', 'planned', '#89dceb', '#89dceb', '#74c7ec', 1, NULL, NULL);
INSERT INTO track VALUES ('modelos-datos', 'Modelos de Datos', 'Relacional, documento, grafo', 'Cómo se modela la información y qué compromete cada modelo.', 'datos-persistencia', 'planned', '#74c7ec', '#74c7ec', '#89b4fa', 0, NULL, NULL);
INSERT INTO track VALUES ('bases-datos', 'Bases de Datos', 'Motores e índices', 'Del árbol B al planificador de consultas: cómo un motor guarda y encuentra.', 'datos-persistencia', 'planned', '#74c7ec', '#74c7ec', '#89b4fa', 1, NULL, NULL);
INSERT INTO track VALUES ('transacciones', 'Transacciones', 'ACID y sus costes', 'Atomicidad, aislamiento y durabilidad: qué promete un motor y cómo lo paga.', 'datos-persistencia', 'planned', '#74c7ec', '#74c7ec', '#89b4fa', 2, NULL, NULL);
INSERT INTO track VALUES ('criptografia', 'Criptografía', 'Cifrar, firmar, verificar', 'Simétrica, asimétrica, hashes y firmas: las primitivas y sus usos correctos.', 'seguridad', 'planned', '#f38ba8', '#f38ba8', '#eba0ac', 0, NULL, NULL);
INSERT INTO track VALUES ('seguridad-sistemas', 'Seguridad de Sistemas', 'Ataques y defensas', 'Superficies de ataque, aislamiento, memoria segura y el modelo de amenazas.', 'seguridad', 'planned', '#f38ba8', '#f38ba8', '#eba0ac', 1, NULL, NULL);
INSERT INTO track VALUES ('aprendizaje-automatico', 'Aprendizaje Automático', 'Modelos que aprenden', 'Del descenso de gradiente a los transformers: qué aprende un modelo y de qué depende.', 'ia-aprendizaje', 'planned', '#b4befe', '#b4befe', '#89b4fa', 0, NULL, NULL);
